"""
Migration data: BIB → Email mapping for BYSD-2026 race
Source: Excel file provided by admin (sexo_emails.xlsx)
Used by: auto-claim logic in athlete registration
"""

BIB_EMAIL_MAP = {
    "001": "lgaitanleal@gmail.com",
    "002": "hamletburgos@hotmail.com",
    "003": "carloscamejo83@gmail.com",
    "004": "tomas.ruizornes@gmail.com",
    "005": "biondi27@gmail.com",
    "006": "minimuri.mexico@gmail.com",
    "007": "coacherbscharf@gmail.com",
    "008": "judelkvargas@gmail.com",
    "009": "angelrondon86@gmail.com",
    "010": "iemdventas@gmail.com",
    "011": "luisemiliocabralrivera@gmail.com",
    "012": "abelperez1912@gmail.com",
    "013": "parrawalterdamian@gmail.com",
    "014": "elcadete8@gmail.com",
    "015": "oli.arellano.campos@gmail.com",
    "016": "aivaliklisjla@gmail.com",
    "017": "aguilarmendizabal@gmail.com",
    "018": "carlosnutrilitesport2009@gmail.com",
    "019": "gapercivaldi@gmail.com",
    "020": "ivaneguiluz@gmail.com",
    "021": "miguelvasquezruns@gmail.com",
    "022": "la.deleon.encarnacion@gmail.com",
    "023": "isabellaroussdomin@gmail.com",
    "024": "alijeronimo@gmail.com",
    "025": "rafael.arthurov@gmail.com",
    "026": "faustobatista21@gmail.com",
    "027": "miriambalaguer13@gmail.com",
    "028": "yosip0507@gmail.com",
    "029": "yesi0811.ym@gmail.com",
    "030": "jimenezbraulio@gmail.com",
    "031": "yeiryssoto11@gmail.com",
    "032": "tommygs90@gmail.com",
    "033": "heldragarib@gmail.com",
    "034": "jgab.rodriguez1@gmail.com",
    "035": "sissymencia@gmail.com",
    "036": "julicanahuate@gmail.com",
    "037": "omy2810@gmail.com",
    "038": "ismaelmorillo25@gmail.com",
    "039": "ambaresmeraldadls@gmail.com",
    "040": "margaretamabel1113@gmail.com",
    "041": "annekeblomer@gmail.com",
    "042": "pascalsterlin@gmail.com",
    "043": "luisnadielperezgonzalez@gmail.com",
    "044": "ajruiz67@gmail.com",
    "045": "daiyishiguetome@gmail.com",
    "046": "ernestovalles1103@gmail.com",
    "047": "orellana.david@gmail.com",
    "048": "simonbolivarcepeda@gmail.com",
    "049": "miltonnunezimbert@gmail.com",
    "050": "kkephasprp@gmail.com",
    "051": "rjfarach@gmail.com",
    "052": "bernardodejesus22@gmail.com",
    "053": "jhoelcam@gmail.com",
    "054": "losgarj007@gmail.com",
    "055": "victorkery@gmail.com",
    "056": "robert.duran1709@gmail.com",
    "057": "epaulinotj@gmail.com",
    "058": "cesar.encarnacion.r@gmail.com",
    "059": "rafael.altuna23@gmail.com",
    "060": "alexandra20049@gmail.com",
    "061": "even.lafay@gmail.com",
    "062": "cjballenilla@hotmail.com",
    "063": "georgecorre300@gmail.com",
    "064": "burgos772@gmail.com",
    "065": "serf42@gmail.com",
    "066": "pablitoclases33@gmail.com",
    "067": "ramonjose0127@gmail.com",
    "068": "oj.arch89@gmail.com",
    "069": "jomamanuelgv@gmail.com",
    "070": "oscarrmoquete@gmail.com",
    "071": "carlosogandomontas@gmail.com",
    "072": "daphneheyaime@gmail.com",
    "073": "mac222330@gmail.com",
    "074": "michelledominguez6@gmail.com",
    "075": "karinaanaortiz@gmail.com",
    "076": "isadelgam@gmail.com",
    "077": "pedrop2954.pt@gmail.com",
    "078": "rommellmorel121@gmail.com",
    "079": "avasquezcolon@gmail.com",
    "080": "jcblevinson@gmail.com",
    "081": "kensey.pichardo@gmail.com",
    "082": "ca.js.chaljub@gmail.com",
    "083": "scheidigsr@gmail.com",
    "084": "armandojosebisono@gmail.com",
    "085": "dirtsurfer.tenerife@hotmail.es",
    "086": "tapiagmt11@gmail.com",
    "087": "melvanegas2@gmail.com",
    "088": "lennysjimenez68@gmail.com",
    "090": "livio2020@gmail.com",
}

# Reverse map: email → BIB (for fast lookup during registration)
EMAIL_BIB_MAP = {email: bib for bib, email in BIB_EMAIL_MAP.items()}
